const ActionTypes = {
    LOADER: 'LOADER',
    SHOWERROR: 'SHOWERROR',
    HIDEERROR: 'HIDEERROR',
    STR: 'STR',
    COUNTRIES: 'COUNTRIES',
    STEPS: 'STEPS',
    SEARCHRESULT: 'SEARCHRESULT',
    SAVE_USER: 'SAVE_USER',
    SEARCHDATA: 'SEARCHDATA',
    USERCREDENTIALS: 'USERCREDENTIALS',
    USERDETAILS: 'USERDETAILS',
    TASKID: 'TASKID',
    TABS: 'TABS',
    USER_DATA: 'USER_DATA',
    HIDETABBAR: 'HIDETABBAR',
    SHOWNAV: 'SHOWNAV',
    LOGINUSERDATA: 'LOGINUSERDATA',
    OWNERPROPERTY: 'OWNERPROPERTY'
}

export default ActionTypes;